# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Kevingimbel"
license = "MIT"
licenselink = "https://github.com/kevingimbel/kevingimbel.com/blob/master/LICENSE.md"
description = "Personal Portfolio theme."
homepage = "https://kevingimbel.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Kevin Gimbel"
  homepage = "https://kevingimbel.com"
