# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "A11y"
license = "MIT"
licenselink = "https://github.com/kevingimbel/hugo-a11y-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://kevingimbel.com/a11y-theme"
tags = ["accessible", "a11y", "clean", "minimalistic", "starter"]
features = ["fully accessible", "full keyboard support", "modern CSS", "multiple color themes"]
min_version = "0.25"

[author]
  name = "Kevin Gimbel"
  homepage = "https://kevingimbel.com"
